### ISSUE TITLE
Authentication error when submitting analyses using just the access token

### ISSUE THREAD

**Issue by josh-reid** [ConsenSys/mythx-vscode#11]
When attempting to submit analyses I receive an authentication error if I am only using the generated access token from my MythX dashboard while keeping the ETH address and password fields blank in the extension settings.

• Provide access token in settings
• Leave ETH address and password fields blank
• Receive authentication error when submitting analysis

<img width="454" alt="Screen Shot 2020-02-01 at 8 12 12 PM" src="https://user-images.githubusercontent.com/41704090/73601434-9f808180-452f-11ea-8fcf-66529911899a.png">
<img width="1024" alt="Screen Shot 2020-02-01 at 8 15 56 PM" src="https://user-images.githubusercontent.com/41704090/73601439-ae673400-452f-11ea-8370-d0d1f40c591c.png">

**Comment by Gtonizuka** [comment]
this should have been fixed with commit 8ae6c87. will close it for now
