### ISSUE TITLE
Context Menu -> MythX: Analyze Contract - always errors with "This not a solidity file (*.sol)"

### ISSUE THREAD

**Issue by tintinweb** [ConsenSys/mythx-vscode#4]
The file is definitely a solidity file ending with *.sol. I have multiple solidity extensions installed.

What type of information would you need to be able to track this down?

extension version 0.4.0
latest vscode
a bunch of solidity extensions installed

cheers,
tin

//ping me on slack

**Comment by Gtonizuka** [comment]
this is likely an issue with the compiler itself (vscode-solidity extension) not MythX. Can you try to compile this contract on its own with MythX extension uninstalled?
