### ISSUE TITLE
Don't prompt for the contract name if there is only one contract in the source unit.

### ISSUE THREAD

**Issue by tintinweb** [ConsenSys/mythx-vscode#6]
When submitting a contract to mythx the extension prompts for the contract name. In case there is only one contract it might jus auto-select the one contract instead of waiting for the user to select it.

steps to reproduce:

1. open a new file with only one contract
2. click the mythx button to submit it for analysis
3. mythx-vscode asks for the contract (there is only one)

![image](https://user-images.githubusercontent.com/2865694/72257523-25ce3580-360c-11ea-8ef3-c5d0c1c2fb9a.png)

**Comment by Gtonizuka** [comment]
This has been added in 0.7.1 I now read the compiled contract and get the Object.keys - if only one key is present thats the default value
